name: daily_planner1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  flutter_spinkit: ^5.2.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Jaldi
      fonts:
        - asset: fonts/Jaldi-Bold.ttf
          weight: 700
        - asset: fonts/Jaldi-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Regular.ttf
          weight: 400
