// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2MmucRuJ7ZnSf-MDxY5sidKUI8hMShBk',
    appId: '1:776197453969:web:93f26d0e6b93301c6ee730',
    messagingSenderId: '776197453969',
    projectId: 'daily-planner-ce0b9',
    authDomain: 'daily-planner-ce0b9.firebaseapp.com',
    storageBucket: 'daily-planner-ce0b9.appspot.com',
    measurementId: 'G-RD7P6RMMPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6hv3wP_jdqo01LfaridV71CHJYLpkQP0',
    appId: '1:776197453969:android:a7d3e485f2651c5d6ee730',
    messagingSenderId: '776197453969',
    projectId: 'daily-planner-ce0b9',
    storageBucket: 'daily-planner-ce0b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0joGeMoK7o3FQ_ix_tvO32NIDbm4vcyE',
    appId: '1:776197453969:ios:122170561d63adc56ee730',
    messagingSenderId: '776197453969',
    projectId: 'daily-planner-ce0b9',
    storageBucket: 'daily-planner-ce0b9.appspot.com',
    iosBundleId: 'com.example.dailyPlanner1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0joGeMoK7o3FQ_ix_tvO32NIDbm4vcyE',
    appId: '1:776197453969:ios:122170561d63adc56ee730',
    messagingSenderId: '776197453969',
    projectId: 'daily-planner-ce0b9',
    storageBucket: 'daily-planner-ce0b9.appspot.com',
    iosBundleId: 'com.example.dailyPlanner1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2MmucRuJ7ZnSf-MDxY5sidKUI8hMShBk',
    appId: '1:776197453969:web:98243c5956715e216ee730',
    messagingSenderId: '776197453969',
    projectId: 'daily-planner-ce0b9',
    authDomain: 'daily-planner-ce0b9.firebaseapp.com',
    storageBucket: 'daily-planner-ce0b9.appspot.com',
    measurementId: 'G-2WK7G8V2ED',
  );
}
